# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\配送管理\rule\获取可选门店列表\1.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT1(HttpRunner):

    config = (
        Config("获取可选门店列表-按品牌搜索")
        .variables(**{"baseUrl": "/storeServer/deliveryManagement"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("$baseUrl/rule/listSelectableStore")
            .post("$baseUrl/rule/listSelectableStore")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json({"brandId": "26000252", "pageNum": 1, "pageSize": 10})
            .extract()
            .with_jmespath("body.data.list[0].storeCode", "storeCode")
            .with_jmespath("body.data.list[0].storeId", "storeId")
            .with_jmespath("body.data.list[0].storeName", "storeName")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT1().test_start()
