# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人紧急联系人更新\15.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人紧急联系人保存.T14_test import TestCaseT14 as T14

from TestCase/APICase.人事系统_H5.候选人招聘模块.查看候选人详情.T4_test import TestCaseT4 as T4


class TestCaseT15(HttpRunner):

    config = (
        Config("候选人紧急联系人更新 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("候选人紧急联系人保存 - 正常返回").call(T14)),
        Step(RunTestCase("查看候选人详情 - 正常返回").call(T4).export(*["emergencyId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/modifyEntrantEmergency")
            .post("/$baseUrlH5/entrant/recruit/modifyEntrantEmergency")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "id": "$emergencyId",
                    "emergencyAddress": "联系地址222",
                    "emergencyMan": "姓名2",
                    "emergencyPhone": "18888888888",
                    "emergencyRelative": "朋友",
                    "entrantId": "$entrantId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT15().test_start()
