# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_WEB\爱挖API模块\接受offer回调接口\18.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT18(HttpRunner):

    config = (
        Config("接受offer回调接口 - 正常返回 - 门店")
        .variables(**{"baseUrl": "ehr-admin"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest(
                "$baseUrl/ivva/callbackAcceptOffer?positionId=10499&recruitId=723237&resumeId=1819337&offerSendLogsId=3282&replyStatus=1"
            )
            .post(
                "$baseUrl/ivva/callbackAcceptOffer?positionId=10499&recruitId=723237&resumeId=1819337&offerSendLogsId=3282&replyStatus=1"
            )
            .with_headers(**{"Content-Type": "application/json"})
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.success", True)
        ),
    ]


if __name__ == "__main__":
    TestCaseT18().test_start()
