# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人基础信息更新\9.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人基础信息保存.T8_test import TestCaseT8 as T8

from TestCase/APICase.人事系统_H5.候选人招聘模块.查看候选人详情.T4_test import TestCaseT4 as T4


class TestCaseT9(HttpRunner):

    config = (
        Config("候选人基础信息更新 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("候选人基础信息保存 - 正常返回").call(T8)),
        Step(RunTestCase("查看候选人详情 - 正常返回").call(T4).export(*["entrantBasicId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/modifyEntrantBasic")
            .post("/$baseUrlH5/entrant/recruit/modifyEntrantBasic")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "id": "$entrantBasicId",
                    "entrantId": "$entrantId",
                    "entrantName": "彭鹏",
                    "entrantMobile": "13570834571",
                    "idCard": "522129198807130016",
                    "cardImageUrl": [
                        {
                            "uri": "test-pd/qmpue2hc42k0-sfz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/qmpue2hc42k0-sfz.png",
                        },
                        {
                            "uri": "test-pd/j1ov1al1v6g0-sfz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/j1ov1al1v6g0-sfz.png",
                        },
                    ],
                    "cardEndDate": "2022-08-31",
                    "cardAddress": "身份证地址testing",
                    "birthDate": "1988-07-13",
                    "constellation": 5,
                    "gender": "0",
                    "nativePlace": "贵州",
                    "marriage": "0",
                    "nation": "0",
                    "politicalStatus": "0",
                    "email": "test@pin-dao.cn",
                    "bankAccount": "66666666666666666",
                    "bankPhotoUrl": [
                        {
                            "uri": "test-pd/12de2tn1vrko0-yhk.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/12de2tn1vrko0-yhk.png",
                        },
                        {
                            "uri": "test-pd/j9l289skhfg0-yhk.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/j9l289skhfg0-yhk.png",
                        },
                    ],
                    "bankId": 0,
                    "bankName": "",
                    "householdType": "0",
                    "address": "现居住地址test${now_time()}",
                    "isNcms": 1,
                    "healthCardDate": "2020-08-31",
                    "healthCardPhotoUrl": [
                        {
                            "uri": "test-pd/oj7t5m9b5es0-jkz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/oj7t5m9b5es0-jkz.png",
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT9().test_start()
