version: "2.0"
services:
  grid:
    build: ./WebChrome/SeleniumGrid
    restart: unless-stopped
    ports:
      - "6044:4444"
    container_name: air_selenium_grid
  webdriver:
    build: ./WebChrome/WebDriver
    environment: 
      VNC_PASSWORD: test123456
      RESOLUTION: 1920x1080
    restart: unless-stopped
    ports:
      - "6080:80"
    links:
      - grid
    container_name: air_web_driver
  airobots:
    build: ./
    volumes:
      - ./:/data/
    links:
      - grid
    container_name: airobots_runner