# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\门店管理\时间方案管理\方案列表\13.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT13(HttpRunner):

    config = (
        Config("方案列表-正常返回-按方案名称搜索")
        .variables(**{"baseUrl": "/", "base_url": ""})
        .base_url("${base_url}")
    )

    teststeps = [
        Step(
            RunRequest(
                "${base_url}/storeServer/store/businessTimeManage/getStoreBusinessTimeList"
            )
            .post(
                "${base_url}/storeServer/store/businessTimeManage/getStoreBusinessTimeList"
            )
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "${token}"}
            )
            .with_json(
                {
                    "businessTimeCode": "",
                    "businessTimeName": "SZ配送时间方案test",
                    "businessTimeType": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                }
            )
            .extract()
            .with_jmespath("body.data.list[0].businessTimeCode", "businessTimeCode")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT13().test_start()
