# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_WEB\候选人招聘模块\查看候选人列表\1.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT1(HttpRunner):

    config = (
        Config("查看候选人列表 - 正常返回")
        .variables(**{"baseUrl": "ehr-admin"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("$baseUrl/entrant/recruit/pageEntrant")
            .post("$baseUrl/entrant/recruit/pageEntrant")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json({"auditStatus": 0, "pageNum": 1, "pageSize": 10})
            .extract()
            .with_jmespath("body.data.list[0].entrantInfoId", "entrantId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT1().test_start()
