# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_WEB\候选人合同模块\合同分页查询\13.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT13(HttpRunner):

    config = (
        Config("合同分页查询 - 正常返回")
        .variables(**{"baseUrl": "ehr-admin"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("$baseUrl/entrant/contract/pageContract")
            .post("$baseUrl/entrant/contract/pageContract")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json({"pageNum": 1, "pageSize": 10, "signStatus": ["4"]})
            .extract()
            .with_jmespath(
                "body.data.list[0].entrantContractCode", "entrantContractCode"
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT13().test_start()
