# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人家庭成员保存\12.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT12(HttpRunner):

    config = (
        Config("候选人家庭成员保存 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/saveEntrantFamily")
            .post("/$baseUrlH5/entrant/recruit/saveEntrantFamily")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                [
                    {
                        "address": "联系地址11",
                        "entrantId": "$entrantId",
                        "familyName": "兄弟1",
                        "familyOrder": "",
                        "occupation": "无业",
                        "phoneNum": "18444444444",
                        "relation": "兄弟",
                    }
                ]
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT12().test_start()
