# NOTE: Generated By HttpRunner v3.1.4
# FROM: .\TestCase/APICase\门店管理\时间方案管理\编辑方案\9.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.门店管理.时间方案管理.方案列表.T13_test import TestCaseT13 as T13


class TestCaseT9(HttpRunner):

    config = (
        Config("编辑方案-正常返回")
        .variables(**{"baseUrl": "/", "base_url": "http://teacore-k8s-test.pin-dao.cn"})
        .base_url("${base_url}")
    )

    teststeps = [
        Step(RunTestCase("方案列表-正常返回-按方案名称搜索").call(T13).export(*["businessTimeCode"])),
        Step(
            RunRequest(
                "${base_url}/storeServer/store/businessTimeManage/modifyStoreBusinessTimeInfo"
            )
            .post(
                "${base_url}/storeServer/store/businessTimeManage/modifyStoreBusinessTimeInfo"
            )
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "businessTimeCode": "${businessTimeCode}",
                    "businessTimeName": "SZ配送时间方案testAuto",
                    "businessTimeRule": [
                        {"days": "1,2,3", "rules": ["09:00", "22:00"], "status": "1"},
                        {"days": "4,5,6", "rules": ["10:00", "22:00"], "status": "1"},
                        {"days": "7", "rules": [], "status": "2"},
                    ],
                    "businessTimeType": "2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT9().test_start()
