# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人教育背景更新\11.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人教育背景保存.T10_test import TestCaseT10 as T10

from TestCase/APICase.人事系统_H5.候选人招聘模块.查看候选人详情.T4_test import TestCaseT4 as T4


class TestCaseT11(HttpRunner):

    config = (
        Config("候选人教育背景更新 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("候选人教育背景保存 - 正常返回").call(T10)),
        Step(RunTestCase("查看候选人详情 - 正常返回").call(T4).export(*["educationId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/modifyEntrantEduction")
            .post("/$baseUrlH5/entrant/recruit/modifyEntrantEduction")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "beginDate": "2020-04-01",
                    "certificateName": "测试证书",
                    "certificatePhotoUrl": [
                        {
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/tfnh1imr2r80-byz.png",
                            "uri": "test-pd/tfnh1imr2r80-byz.png",
                        }
                    ],
                    "endDate": "2020-08-01",
                    "entrantId": "$entrantId",
                    "id": "$educationId",
                    "major": "测试专业",
                    "schoolName": "测试1",
                    "topDegree": 6,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT11().test_start()
