# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人其他说明保存\16.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT16(HttpRunner):

    config = (
        Config("候选人其他说明保存 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/saveEntrantOther")
            .post("/$baseUrlH5/entrant/recruit/saveEntrantOther")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "entrantId": "$entrantId",
                    "id": 0,
                    "isCriminal": "0",
                    "isCriminalDetail": "",
                    "isHired": "0",
                    "isHiredDetail": "",
                    "isInfluential": "1",
                    "isInfluentialDetail": "无",
                    "isOtherLabor": "0",
                    "isOtherLaborDetail": "",
                    "isRecommend": "0",
                    "isRecommendDetail": "",
                    "isRelative": "0",
                    "isRelativeDetail": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT16().test_start()
