# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人其他说明更新\17.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人其他说明保存.T16_test import TestCaseT16 as T16

from TestCase/APICase.人事系统_H5.候选人招聘模块.查看候选人详情.T4_test import TestCaseT4 as T4


class TestCaseT17(HttpRunner):

    config = (
        Config("候选人其他说明更新 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("候选人其他说明保存 - 正常返回").call(T16)),
        Step(RunTestCase("查看候选人详情 - 正常返回").call(T4).export(*["otherId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/modifyEntrantOther")
            .post("/$baseUrlH5/entrant/recruit/modifyEntrantOther")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "entrantId": "$entrantId",
                    "id": "$otherId",
                    "isCriminal": "0",
                    "isCriminalDetail": "",
                    "isHired": "0",
                    "isHiredDetail": "",
                    "isInfluential": "1",
                    "isInfluentialDetail": "无",
                    "isOtherLabor": "0",
                    "isOtherLaborDetail": "",
                    "isRecommend": "undefined",
                    "isRecommendDetail": "",
                    "isRelative": "0",
                    "isRelativeDetail": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT17().test_start()
