# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase\APICase\人事系统_H5\候选人招聘模块\查询候选人列表\3.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT3(HttpRunner):

    config = (
        Config("查询候选人列表-客户端（候选人） - 正常返回")
        .variables(
            **{
                "baseUrlH5": "/ehr-entrant",
                "base_url": "https://operate-test-api.pin-dao.cn",
                "token_h5": "${get_h5_token($base_url)}",
            }
        )
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest(
                "/$baseUrlH5/entrant/recruit/queryEntrantMain?entrantMobile=13570834571"
            )
            .post(
                "/$baseUrlH5/entrant/recruit/queryEntrantMain?entrantMobile=13570834571"
            )
            .with_headers(**{"Authorization": "$token_h5"})
            .with_json({})
            .extract()
            .with_jmespath("body.data.entrantId", "entrantId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT3().test_start()
