# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase\APICase\人事系统_H5\候选人招聘模块\获取候选人初始化教育信息\6.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase.APICase.人事系统_H5.候选人招聘模块.查询候选人列表.T3_test import TestCaseT3 as T3


class TestCaseT6(HttpRunner):

    config = (
        Config("获取候选人初始化教育信息 - 正常返回")
        .variables(
            **{
                "baseUrlH5": "/ehr-entrant",
                "base_url": "https://operate-test-api.pin-dao.cn",
                "token_h5": "${get_h5_token($base_url)}",
            }
        )
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("查询候选人列表-客户端（候选人） - 正常返回").call(T3).export(*["entrantId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/getInitEntrantEducation")
            .post("/$baseUrlH5/entrant/recruit/getInitEntrantEducation")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json({"entrantId": "$entrantId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT6().test_start()
