# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人附件上传保存\20.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT20(HttpRunner):

    config = (
        Config("候选人附件上传保存 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/saveEntrantAppendix")
            .post("/$baseUrlH5/entrant/recruit/saveEntrantAppendix")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "currentStatus": "",
                    "entrantId": "$entrantId",
                    "householdProveUrl": [{"uri": "test-pd/qe53uolbhas0-sfz.png"}],
                    "leaveProveUrl": [{"uri": "test-pd/vphl4tsgee00-byz.png"}],
                    "pageType": "",
                    "physicalFormUrl": [],
                    "schoolProveUrl": [{"uri": "test-pd/k0gtnu655800-byz.png"}],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT20().test_start()
