# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\配送管理\rule\13.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT13(HttpRunner):

    config = (
        Config("获取可选配送商取消原因-正常返回")
        .variables(
            **{"baseUrl": "/storeServer/deliveryManagement", "deliverTypeId": "1"}
        )
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("$baseUrl/rule/listCancelItemByDeliverTypeId")
            .get("$baseUrl/rule/listCancelItemByDeliverTypeId")
            .with_params(**{"deliverTypeId": "$deliverTypeId"})
            .with_headers(**{"Authorization": "$token"})
            .extract()
            .with_jmespath("body.data[0].id", "reasonId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT13().test_start()
