# NOTE: Generated By HttpRunner v3.1.4
# FROM: .\TestCase/APICase\人事系统_WEB\候选人招聘模块\查看候选人详情\2.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_WEB.候选人招聘模块.查看候选人列表.T1_test import TestCaseT1 as T1


class TestCaseT2(HttpRunner):

    config = (
        Config("查看候选人详情 - 正常返回")
        .variables(
            **{
                "baseUrl": "ehr-admin",
                "base_url": "https://operate-test-api.pin-dao.cn",
            }
        )
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("查看候选人列表 - 正常返回").call(T1).export(*["entrantId"])),
        Step(
            RunRequest("$baseUrl/entrant/recruit/findEntrant")
            .post("$baseUrl/entrant/recruit/findEntrant")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json({"entrantId": "$entrantId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT2().test_start()
