# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\门店管理\时间方案管理\添加方案\8.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT8(HttpRunner):

    config = (
        Config("添加方案-正常返回")
        .variables(**{"baseUrl": "/", "base_url": ""})
        .base_url("${base_url}")
    )

    teststeps = [
        Step(
            RunRequest(
                "${base_url}/storeServer/store/businessTimeManage/addStoreBusinessTimeInfo"
            )
            .post(
                "${base_url}/storeServer/store/businessTimeManage/addStoreBusinessTimeInfo"
            )
            .with_headers(**{"Content-Type": "application/json"})
            .with_json(
                {
                    "businessTimeName": "SZ配送时间方案test",
                    "businessTimeRule": [
                        {"days": "1,2,3", "rules": ["09:00", "22:00"], "status": "1"},
                        {"days": "4,5,6", "rules": ["10:00", "22:00"], "status": "1"},
                        {"days": "7", "rules": ["10:00", "22:00"], "status": "2"},
                    ],
                    "businessTimeType": 2,
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT8().test_start()
