# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_WEB\候选人合同模块\查询业务分类列表\15.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_WEB.候选人合同模块.合同分页查询.T13_test import TestCaseT13 as T13


class TestCaseT15(HttpRunner):

    config = (
        Config("查询业务分类列表 - 正常返回")
        .variables(**{"baseUrl": "ehr-admin"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("合同分页查询 - 正常返回").call(T13).export(*["entrantContractCode"])),
        Step(
            RunRequest("$baseUrl/entrant/contract/listCategory")
            .post("$baseUrl/entrant/contract/listCategory")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json({"entrantContractCode": "$entrantContractCode"})
            .extract()
            .with_jmespath("body.data[0].contractCategoryId", "contractCategoryId")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT15().test_start()
