# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人提交信息\22.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.查询候选人列表.T3_test import TestCaseT3 as T3

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人基础信息更新.T9_test import TestCaseT9 as T9

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人教育背景更新.T11_test import TestCaseT11 as T11

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人工作经历更新.T19_test import TestCaseT19 as T19

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人家庭成员更新.T13_test import TestCaseT13 as T13

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人紧急联系人更新.T15_test import TestCaseT15 as T15

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人其他说明更新.T17_test import TestCaseT17 as T17

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人附件上传更新.T21_test import TestCaseT21 as T21


class TestCaseT22(HttpRunner):

    config = (
        Config("候选人提交信息 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("查询候选人列表-客户端（候选人） - 正常返回").call(T3).export(*["entrantId"])),
        Step(RunTestCase("候选人基础信息更新 - 正常返回").call(T9)),
        Step(RunTestCase("候选人教育背景更新 - 正常返回").call(T11)),
        Step(RunTestCase("候选人工作经历更新 - 正常返回").call(T19)),
        Step(RunTestCase("候选人家庭成员更新 - 正常返回").call(T13)),
        Step(RunTestCase("候选人紧急联系人更新 - 正常返回").call(T15)),
        Step(RunTestCase("候选人其他说明更新 - 正常返回").call(T17)),
        Step(RunTestCase("候选人附件上传更新 - 正常返回").call(T21)),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/entrantSubmit")
            .post("/$baseUrlH5/entrant/recruit/entrantSubmit")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json({"entrantId": "$entrantId"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT22().test_start()
