# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人附件上传更新\21.yaml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from TestCase/APICase.人事系统_H5.候选人招聘模块.候选人附件上传保存.T20_test import TestCaseT20 as T20

from TestCase/APICase.人事系统_H5.候选人招聘模块.查看候选人详情.T4_test import TestCaseT4 as T4


class TestCaseT21(HttpRunner):

    config = (
        Config("候选人附件上传更新 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(RunTestCase("候选人附件上传保存 - 正常返回").call(T20)),
        Step(RunTestCase("查看候选人详情 - 正常返回").call(T4).export(*["appendixId"])),
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/modifyEntrantAppendix")
            .post("/$baseUrlH5/entrant/recruit/modifyEntrantAppendix")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "id": "$appendixId",
                    "entrantId": "$entrantId",
                    "householdProveUrl": [
                        {
                            "uri": "test-pd/qe53uolbhas0-sfz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/qe53uolbhas0-sfz.png",
                        }
                    ],
                    "leaveProveUrl": [
                        {
                            "uri": "test-pd/vphl4tsgee00-byz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/vphl4tsgee00-byz.png",
                        }
                    ],
                    "schoolProveUrl": [
                        {
                            "uri": "test-pd/k0gtnu655800-byz.png",
                            "url": "https://test-pd.oss-cn-beijing.aliyuncs.com/test-pd/k0gtnu655800-byz.png",
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT21().test_start()
