# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCases/APICase/api_demo/login.yml


import pytest


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):
    @pytest.mark.first
    def test_start(self):
        super().test_start()

    config = (
        Config("登录")
        .variables(**{"base_url": "https://td.dia03.com"})
        .base_url("$base_url")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("/v1/login")
            .post("/v1/login")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                    "content-length": "48",
                    "content-type": "application/json;charset=UTF-8",
                    "dnt": "1",
                    "origin": "https://td.dia03.com",
                    "referer": "https://td.dia03.com/user/login?redirect=%2F",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-origin",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                }
            )
            .with_json({"password": "test1234", "username": "13279297419"})
            .extract()
            .with_jmespath("body.data.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
