# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\配送管理\order\根据条件筛选参数获取配送订单信息\18.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT18(HttpRunner):

    config = (
        Config("根据条件筛选参数获取配送订单信息-按品牌和配送状态查询")
        .variables(**{"baseUrl": "/storeServer/deliveryManagement"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("$baseUrl/order/listDeliveryOrder")
            .post("$baseUrl/order/listDeliveryOrder")
            .with_headers(
                **{"Authorization": "$token", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "brandId": "26000252",
                    "deliveryStatus": "$deliveryStatus",
                    "pageNum": 1,
                    "pageSize": 10,
                }
            )
            .extract()
            .with_jmespath("body.data.list[0].deliveryNo", "deliveryNo")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT18().test_start()
