# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\人事系统_H5\候选人招聘模块\候选人紧急联系人保存\14.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT14(HttpRunner):

    config = (
        Config("候选人紧急联系人保存 - 正常返回")
        .variables(**{"baseUrlH5": "/ehr-entrant"})
        .base_url("$base_url")
    )

    teststeps = [
        Step(
            RunRequest("/$baseUrlH5/entrant/recruit/saveEntrantEmergency")
            .post("/$baseUrlH5/entrant/recruit/saveEntrantEmergency")
            .with_headers(
                **{"Authorization": "$token_h5", "Content-Type": "application/json"}
            )
            .with_json(
                {
                    "emergencyAddress": "联系地址222",
                    "emergencyMan": "姓名1",
                    "emergencyPhone": "18888888888",
                    "emergencyRelative": "朋友",
                    "entrantId": "$entrantId",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT14().test_start()
