# NOTE: Generated By HttpRunner v3.1.4
# FROM: TestCase/APICase\门店管理\门店信息管理\门店列表\18.yaml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseT18(HttpRunner):

    config = (
        Config("门店列表-正常返回")
        .variables(**{"baseUrl": "/", "base_url": ""})
        .base_url("${base_url}")
    )

    teststeps = [
        Step(
            RunRequest(
                "${base_url}/storeServer/store/storeBaseInfo/getStoreBaseInfoList"
            )
            .post("${base_url}/storeServer/store/storeBaseInfo/getStoreBaseInfoList")
            .with_headers(
                **{"Content-Type": "application/json", "Authorization": "${token}"}
            )
            .with_json(
                {
                    "brandId": 0,
                    "businessTimeRuleId": "",
                    "businessTypeId": "",
                    "cityId": 0,
                    "countryId": 86,
                    "departAreaId": 0,
                    "dispatchRuleId": "",
                    "isManyStalls": 0,
                    "isSupplyAutoOrder": 0,
                    "isSupplyDispatch": 0,
                    "isSupplyEatIn": 0,
                    "isSupplyPreOrder": 0,
                    "isWarmUpTime": 0,
                    "operationType": 0,
                    "pageNum": 1,
                    "pageSize": 10,
                    "provinceId": 0,
                    "status": 0,
                    "storeAddress": "",
                    "storeCode": 91893,
                    "storeCompanyId": "",
                    "storeName": "",
                }
            )
            .extract()
            .with_jmespath("body.data.data[0].id", "id")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseT18().test_start()
